### ISSUE TITLE
此版本clash无法正确支持 rule-set 外部规则

### ISSUE THREAD

**Issue by Well2333** [China-Deng/ClashForAndroid#2]
如题，对于包含 ruleprovider 和 ruleset 的规则文件，此版本 clash 无法正常解析，但cfa原版是可以正常解析的。

由于 ruleset 是 Clash Premium 内核的特有功能，个人推测可能是打包的 clash 内核是常规内核导致的问题。

**Comment by China-Deng** [comment]
> 如题，对于包含 ruleprovider 和 ruleset 的规则文件，此版本 clash 无法正常解析，但cfa原版是可以正常解析的。
> 
> 由于 ruleset 是 Clash Premium 内核的特有功能，个人推测可能是打包的 clash 内核是常规内核导致的问题。

可以尝试替换库文件重新打包APK（好像有人成功过），或者试试CMFA能否支持，CMFA现在也支持流量显示了

**Comment by China-Deng** [comment]
> > > 如题，对于包含 ruleprovider 和 ruleset 的规则文件，此版本 clash 无法正常解析，但cfa原版是可以正常解析的。
> > > 由于 ruleset 是 Clash Premium 内核的特有功能，个人推测可能是打包的 clash 内核是常规内核导致的问题。
> > 
> > 
> > 可以尝试替换库文件重新打包APK（好像有人成功过），或者试试CMFA能否支持，CMFA现在也支持流量显示了
> 
> 我查看了一下cfa，发现发布版有 foss 和 premium 两种，可能此版本默认采用了 foss 版吧。我由于没怎么接触过软件编译就算了。
> 
> 另外， cmfa 的仓库地址是否能够提供一下呢，我直接查询没有找到与 clash 相关的仓库或项目。

我替换内核打包了一个 你可以尝试使用试试，能否使用，不行我就删除掉，cmfa：https://github.com/metacubex/clash.meta

**Comment by Well2333** [comment]
此版本是可以正常识别外部资源的，但无法正常下载和读取配置文件的外部资源。

![InkedScreenshot_2023-01-09-14-44-35-298_com github kr328 clash dj foss](https://user-images.githubusercontent.com/40534114/211254004-2303833f-b85e-4f1d-b854-6eef54690d27.jpg)

[profile.txt](https://github.com/China-Deng/ClashForAndroid/files/10370981/profile.txt)

这是我在用的配置文件去掉节点信息后的样本文件，url: <https://github.com/China-Deng/ClashForAndroid/files/10370981/profile.txt> ，可以用作测试。

在测试十余次后，仅出现了一次成功，但可惜的是成功的那次是样本文件而不是正式文件，并且此后也没有一次成功过。不过至少证明了clash内核是完整的，文件仅出现在下载上。

虽然看起来像是网络连接的问题，不过我在 cfa原版、cfw 和 openclash 里面均可以正常导入并识别，均无一次失败，因此我认为可能是软件内部的连接问题。

此外，cmfa 是使用 meta 内核的，而外部资源（rule-set）是 premium 特有的功能，因此 cmfa 理论上是无法支持此功能的。

**Comment by China-Deng** [comment]
> 此版本是可以正常识别外部资源的，但无法正常下载和读取配置文件的外部资源。
> 
> ![InkedScreenshot_2023-01-09-14-44-35-298_com github kr328 clash dj foss](https://user-images.githubusercontent.com/40534114/211254004-2303833f-b85e-4f1d-b854-6eef54690d27.jpg)
> 
> [profile.txt](https://github.com/China-Deng/ClashForAndroid/files/10370981/profile.txt)
> 
> 这是我在用的配置文件去掉节点信息后的样本文件，url: https://github.com/China-Deng/ClashForAndroid/files/10370981/profile.txt ，可以用作测试。
> 
> 在测试十余次后，仅出现了一次成功，但可惜的是成功的那次是样本文件而不是正式文件，并且此后也没有一次成功过。不过至少证明了clash内核是完整的，文件仅出现在下载上。
> 
> 虽然看起来像是网络连接的问题，不过我在 cfa原版、cfw 和 openclash 里面均可以正常导入并识别，均无一次失败，因此我认为可能是软件内部的连接问题。
> 
> 此外，cmfa 是使用 meta 内核的，而外部资源（rule-set）是 premium 特有的功能，因此 cmfa 理论上是无法支持此功能的。

那么可能无法支持了，很抱歉我对Clash的内核编译是不熟悉的

**Comment by Well2333** [comment]
很遗憾，只能等cfa自己更新了。

**Comment by Well2333** [comment]
我刚刚查询了一下 meta 内核的 [文档](https://docs.metacubex.one/example/ex1#dai-li-zu-pei-zhi)，发现 meta 内核已经支持了外部资源（rule-set）的使用。
现在使用 cmfa 是可以正常导入我的配置文件的，并且也有流量显示。
再次感谢您提供的帮助！

**Comment by China-Deng** [comment]
> 很遗憾，只能等cfa自己更新了。

经过询问 meta核是支持的，你尝试一下
